version: "3.7"
services:

  app:
    build:
      args:
        user: user
        uid: 1000
      context: ./docker-compose
      dockerfile: php.Dockerfile
    image: app_docker
    container_name: app_docker_app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app_network

  node:
    build:
      context: ./docker-compose
      dockerfile: node.Dockerfile
    image: app_node
    container_name: app_node
    volumes:
      - ./:/var/www
      - ./node_modules:/var/www/node_modules
    networks:
      - app_network

  mysql:
    image: mysql:5.7
    container_name: app_docker_mysql
    restart: always
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - ./docker-compose/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - "3306:3306"
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: app_phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: app_docker_mysql
      PMA_USER: root
      PMA_PASSWORD: password
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: app_docker_nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - app_network

  mailhog:
    image: mailhog/mailhog
    container_name: app_mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - app_network

  composer:
    container_name: app_composer
    build:
      context: docker-compose
      dockerfile: composer.Dockerfile
    volumes:
      - ./:/var/www

  ngrok:
    image: ngrok/ngrok:latest
    container_name: doctrine_docker_ngrok
    restart: unless-stopped
    depends_on:
      - nginx
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./docker-compose/ngrok/ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    networks:
      - doctrine_network

networks:
  app_network:
    driver: bridge