version: "2"
services:

  app:
    build:
      args:
        user: user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: app_docker
    container_name: app_docker_app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  mysql:
    image: mysql:5.7
    container_name: app_docker_mysql
    restart: always
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  nginx:
    image: nginx:latest
    container_name: app_docker_nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
