version: "3.7"
services:

  app:
    build:
      args:
        user: user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: app_docker
    container_name: app_docker_app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app_network

  mysql:
    image: mysql:5.7
    container_name: app_docker_mysql
    restart: always
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - ./docker-compose/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ttt-phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: app_docker_mysql
      PMA_USER: user
      PMA_PASSWORD: password
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: app_docker_nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - app_network

  mailhog:
    image: mailhog/mailhog
    container_name: app_mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - app_network

networks:
  app_network:
    driver: bridge